"""Configuration constants for the elevator simulation."""

# Screen settings
SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 800
SCROLL_SPEED = 20

# Floor settings
FLOOR_WIDTH = 250
FLOOR_HEIGHT = 60
SPACER_HEIGHT = 7
START_X_POS_FLOOR = 60
SEC_FOR_FLOOR = 0.5
PIX_PER_SEC = FLOOR_HEIGHT / SEC_FOR_FLOOR
IMG_FLOOR = "assets/images/building.png"

# Elevator settings
START_X_POS_ELV = START_X_POS_FLOOR + FLOOR_WIDTH + 10
ELV_WIDTH = 50
ELV_HEIGHT = FLOOR_HEIGHT - 10
DIFF_ELV = ELV_WIDTH
NUM_ELV = 3
IMG_ELV = "assets/images/elv.png"
MP3 = "assets/mp3_file/ding.mp3"
PAUSE = 2

# Button settings
SIZE_BUTTON = int(FLOOR_HEIGHT / 3)
SIZE_BUTTON_NUM = SIZE_BUTTON
X_START_POS_BUTTON = START_X_POS_FLOOR + (FLOOR_WIDTH) / 2
MID_Y_POS = FLOOR_HEIGHT / 2
X_POS_TIMER = START_X_POS_FLOOR + 5

# Building settings
BUILDING_CONFIGS = [(9, 25), (0, 6), (2, 0), (0, 6), (2, 10), (1, 6), (1, 30)]
_MAX_BUILDING_HEIGHT = max(config[1] * FLOOR_HEIGHT for config in BUILDING_CONFIGS)
MAX_BUILDING_HEIGHT = max(_MAX_BUILDING_HEIGHT, SCREEN_HEIGHT)
ZERO_FLOOR = MAX_BUILDING_HEIGHT - FLOOR_HEIGHT + SPACER_HEIGHT

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
COL_BUTTON_ON = GREEN
COL_BUTTON_OFF = BLACK